name: Bug report
description: Create an issue to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the necessary information to expedite the response.
  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    attributes:
      label: Software Version 
      description: Software version, branch, or tag in the Open Edge Platform Repository
      placeholder: v1.2.0 / Master Branch / tag v2025.2.0-rc3
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Ubuntu 20.04 (LTS)
        - Ubuntu 22.04 (LTS)
        - Ubuntu 24.04 (LTS)
        - Windows System
        - Other (Please specify in description)
    validations:
      required: true

  - type: textarea
    attributes:
      label: System Setup
      description: Describe your system and software setup. Include any critical video, audio, and model files.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducible Steps
      description: Describe how we can reproduce your issue.
    validations:
      required: true
